UPDATE TRAINER
SET PhoneNo = 'newPhoneNumber'
WHERE SSN='SSN2';

UPDATE SCHEDULE
SET GymRoom = 'R4'
WHERE GymRoom = 'R2';

DELETE FROM COURSE
WHERE CId IN (SELECT CId
		FROM SCHEDULE S
		GROUP BY CId
		HAVING COUNT(*) = 1);

DELETE FROM TRAINER
WHERE SSN = 'SSN1';