SET storage_engine=InnoDB; 
CREATE DATABASE IF NOT EXISTS GYM;
use GYM;
SET FOREIGN_KEY_CHECKS=1;

DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS TRAINER;

CREATE TABLE TRAINER ( SSN	CHAR(16) PRIMARY KEY,
			Name	CHAR(15) NOT NULL,
			Surname  CHAR(15) NOT NULL,
			DateOfBirth DATE NOT NULL,
			Email	CHAR(30) NOT NULL
				CHECK (Email LIKE '%@%'),
			PhoneNo CHAR(15) NULL
			);

CREATE TABLE COURSE(CId	CHAR(5) PRIMARY KEY,
			Name	CHAR(50) NOT NULL,
			Type	CHAR(50) NOT NULL,
			Level	SMALLINT NOT NULL CHECK(Level > 0)
			);

CREATE TABLE SCHEDULE(SSN	CHAR(16) NOT NULL,
			Day	CHAR(10) NOT NULL
				CHECK (Day in ('Monday', 'Tuesday', 'Wednesday',
				'Thursday', 'Friday', 'Saturday', 'Sunday')),
			StartTime TIME NOT NULL,
			Duration SMALLINT CHECK(Duration > 0 AND Duration <=60),
			CId	CHAR(5) NOT NULL,
			GymRoom CHAR(5) NOT NULL,
			PRIMARY KEY (SSN, Day, StartTime),
			FOREIGN KEY (SSN) REFERENCES TRAINER(SSN)
				ON UPDATE CASCADE
				ON DELETE CASCADE,
			FOREIGN KEY (CId) REFERENCES COURSE(CId)
				ON UPDATE CASCADE
				ON DELETE CASCADE
			);
			
